language: php

sudo: false
dist: trusty

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    fast_finish: true
    allow_failures:
      - php: 5.6
      - php: nightly

script: composer test
