language: php

sudo: false
dist: trusty

php:
  - 7.2
  - 7.3

env:
  - ONTRAVIS=1

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    fast_finish: true
    allow_failures:
      - php: nightly

before_script:
  - composer install

script: composer test
