language: php

sudo: false
dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4

env:
  - ONTRAVIS=1

cache:
  directories:
    - $HOME/.composer/cache

matrix:
    fast_finish: true
    allow_failures:
      - php: 7.4

before_script:
  - composer install

script: composer test
